conversations/urls.py
from django.urls import path
from .views import create_conversation, inbox, detail

app_name = 'conversation'

urlpatterns = [
    path('<int:item_pk>/', create_conversation, name='new'),
    path('detail/<int:conversation_pk>/', detail, name='detail'),
    path('inbox/', inbox, name='inbox'),
]

core/urls.py
from django.urls import path, include
from .views import (
    index,
    about,
    contact,
    privacy,
    term_of_use,
    signup_view,
    CustomLoginView,
    CustomLogoutView,
    email_exist_with_us,
)

urlpatterns = [
    path("", index, name="home"),
    path("about/", about, name="about"),
    path("contact/", contact, name="contact"),
    path("privacy/", privacy, name="privacy"),
    path("term/", term_of_use, name="term"),
    path("signup/", signup_view, name="signup"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    # Paths for Google authentication
    path("accounts/social/signup/", email_exist_with_us, name="email_exist_with_us"),
    path("accounts/", include("allauth.urls")),
]

dashboard/urls.py
from django.urls import path
from .views import index

app_name = 'dashboard'

urlpatterns = [
    path('', index, name='index'),
]

marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # paths to views
    path("", include("core.urls")),
    path("items/", include("item.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("conversation/", include("conversations.urls")),
    # paths to admin
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    # Internal validation for our sinup form
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("The submited email  was already registered!")
        return email

core/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib import messages
from django.urls import reverse_lazy
from django.shortcuts import redirect, render
from item.models import Category, Item
from .forms import SignUpForm


def index(request):
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()
    return render(
        request, "core/index.html", context={"items": items, "categories": categories}
    )


def about(request):
    return render(request, "core/about.html")


def contact(request):
    return render(request, "core/contact.html")


def privacy(request):
    return render(request, "core/privacy.html")


def term_of_use(request):
    return render(request, "core/term.html")


class CustomLoginView(LoginView):
    template_name = 'core/login.html'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('home')


class CustomLogoutView(LogoutView):
    next_page = 'login'


def signup_view(request):
    form = SignUpForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, 'User successfully created, use your credentials for logging in')
            return redirect('login')

    return render(request, "core/signup.html", {"form": form})


# Validation For Google registration
def email_exist_with_us(request):
    messages.error(request, 'This email was registered with us! Try with your password')
    return redirect('login')

core/templates/core/about.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}About Us Page{% endblock title %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-8">
                <h2>About Us</h2>
                <p>As a passionate Python Django developer, I am driven by my love for coding and my desire to create robust and efficient web applications. Python and Django have become the cornerstone of my development journey, providing me with the tools and frameworks to bring my ideas to life.
                    With Python's clean syntax and powerful capabilities, I am able to write elegant and maintainable code that is both readable and efficient. The versatility of the language allows me to tackle a wide range of projects, from small-scale web applications to large-scale enterprise systems.
                    Django, on the other hand, empowers me to build web applications rapidly and securely. Its batteries-included approach provides me with a rich set of features and tools right out of the box, saving me time and effort in the development process. The Django ORM (Object-Relational Mapping) allows me to work with databases seamlessly, while the templating engine simplifies the presentation layer.
                    What truly fuels my passion for Python and Django development is the ability to bring ideas to life and create meaningful solutions. 
                </p>
                <p>
                    In conclusion, as a passionate Python Django developer, I am committed to leveraging the power of these technologies to build innovative, robust, and efficient web applications that make a positive impact. I look forward to taking on new challenges, pushing boundaries, and continually honing my skills to deliver exceptional results.
                </p>
            </div>
            <div class="col-md-4">
                <img src="{% static 'core\images\man.jpg' %}" class="img-fluid rounded" alt="Man-Programing">
            </div>
        </div>
    </div>
{% endblock content %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <title>{% block title %}{% endblock title %}</title>
</head>
<style>
    .circle-number {
        width: 1.5em;
        height: 1.5em;
        background-color: red;
        border-radius: 50%;
        display: flex;
        justify-content: center;
        align-items: center;
        color: white;
        position: relative;
    }

    .inbox{
        position: relative;
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .inbox span{
        position: absolute;
        top: -1.2em;
    }

    @media (max-width: 575px) {
        .cont-nav{
            display: flex !important;
            justify-content: center !important;
            align-items: center!important;
        }
        .navbar-nav {
            flex-direction: row !important;
        }
        .cont-nav > .cont-ul{
            justify-content: center !important;
        }
    }
</style>
<body>
    <div class="container d-flex justify-content-center mt-1">
        <nav class="navbar navbar-expand-lg navbar-light bg-light" style="width: 100%;">
            <div class="container-fluid cont-nav">
                <a class="navbar-brand fst-italic" href="{% url 'home' %}" style="font-size: 2em;">
                    <i style="color: #0d6efd;" class="bi bi-shop"></i> MyMarketPlace
                </a>
                <div class="collapse navbar-collapse d-flex justify-content-end cont-ul" id="navbarNav">
                    <ul class="navbar-nav d-flex flex-wrap flex-sm-row flex-column gap-2">
                        <li class="nav-item">
                        <a class="btn btn-secondary" href="{% url 'new_item' %}">New item</a>
                        </li>
                        <li class="nav-item">
                        <a class="btn btn-danger" href="{% url 'search' %}">Browse</a>
                        </li>
                        {% if request.user.is_authenticated %}
                            <li class="nav-item">
                                <a class="btn btn-secondary" href="{% url 'dashboard:index' %}">Dashboard</a>
                            </li>    
                            <li class="nav-item">
                                <a class="{% if num_messages %}new-messages{% endif %} inbox btn btn-primary text" href="{% url 'conversation:inbox' %}">
                                    Inbox
                                    {% if num_messages %}
                                        <span class="circle-number new-messages">{{num_messages}}</span>
                                    {% endif %}
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-secondary" href="{% url 'logout' %}">Logout</a>
                            </li>    
                            <li class="nav-item">
                                <i class="bi bi-person-fill" style="font-size: 1.5em; color:#38E54D">
                                    {{request.user}}
                                </i>
                            </li>    
                        {% else %}
                            <li class="nav-item">
                                <a class="btn btn-primary" href="{% url 'signup' %}">Sign up</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-secondary" href="{% url 'login' %}">Login</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>     
    </div>

    <!-- Information about new messages -->
    <div id="messages-cont" class="container d-none">
        {% for message in filtered_messages %}
            <ul class="me-5">
                <li style="list-style: none;">
                    <a href="{% url 'conversation:detail' message.conversation_id %}" style="text-decoration: none;">
                        From {{message.sender}} about {{message.conversation.item}}
                    </a>
                </li>
            </ul>        
        {% endfor %}
        <a href="{% url 'conversation:inbox' %}" style="text-decoration: none; color: #F94A29;">
            <strong>Go to inbox <i class="bi bi-envelope" style="font-size: 1.3em;"></i></strong>
        </a>
    </div>
    
    <!-- Block content for templates -->
    {% block content %}{% endblock content %}
    <!-- End of block content -->

    <!-- Footer --> 
    <div class="mt-5">
        <footer class="text-center text-white" style="background-color: #3f51b5">
            <div class="container">
            <section class="mt-5">
                <div class="row text-center d-flex justify-content-center pt-5">
                    <div class="col-md-2">
                        <h6 class="text-uppercase font-weight-bold">
                        <a href="{% url 'home' %}" class="text-white">Home</a>
                        </h6>
                    </div>
                    <div class="col-md-2">
                        <h6 class="text-uppercase font-weight-bold">
                        <a href="{% url 'about' %}" class="text-white">About us</a>
                        </h6>
                    </div>
                    <div class="col-md-2">
                        <h6 class="text-uppercase font-weight-bold">
                        <a href="{% url 'contact' %}" class="text-white">Contact</a>
                        </h6>
                    </div>
                    <div class="col-md-2">
                        <h6 class="text-uppercase font-weight-bold">
                        <a href="{% url 'privacy' %}" class="text-white">Privacy policy</a>
                        </h6>
                    </div>
                    <div class="col-md-2">
                        <h6 class="text-uppercase font-weight-bold">
                        <a href="{% url 'term' %}" class="text-white">Term of use</a>
                        </h6>
                    </div>
                </div>
            </section>
            <hr class="my-3" />

            <section>
                <div class="row d-flex justify-content-center">
                <div class="col-lg-8">
                    <p style="text-align: left;">
                        Welcome to our marketplace, your one-stop destination for all 
                        your shopping needs. We take pride in offering a diverse range 
                        of high-quality products to cater to every customer's taste and 
                        preferences. Whether you're looking for fashion apparel, electronics, 
                        home decor, or unique gifts, we've got you covered. Our platform 
                        connects buyers and sellers from around the world, providing a seamless 
                        shopping experience. Discover a wide selection of products, explore new trends, 
                        and shop with confidence knowing that we prioritize customer satisfaction. 
                    </p>
                </div>
                </div>
            </section>

            <!-- Section: Social -->
            <section class="text-center mb-3">
                <a href="https://www.facebook.com/profile.php?id=100093136788056" class="text-white me-4"><i class="bi bi-facebook"></i></a>
                <a href="https://twitter.com/frako789" class="text-white me-4"><i class="bi bi-twitter"></i></a>
                <a href="https://www.instagram.com/frako789/" class="text-white me-4"><i class="bi bi-instagram"></i></a>
                <a href="https://www.linkedin.com/in/francisco-bojorque-857147187/" class="text-white me-4"><i class="bi bi-linkedin"></i></a>
                <a href="https://github.com/frakopy" class="text-white me-4"><i class="bi bi-github"></i></a>
            </section>
            <!-- Section: Social -->
            </div>
            <div class="text-center p-3"style="background-color: rgba(0, 0, 0, 0.2)">
            © 20203 Copyright:
            <a class="text-white" href="#">frako789@gmail.com</a>
            </div>
        </footer>
    </div>
    <!-- Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <!-- SweetAlert -->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- Custom Script -->
    <script>
        const inbox = document.getElementsByClassName("inbox")[0];
        const messageContainer = document.getElementById("messages-cont");

        console.log(messageContainer.innerHTML);

        inbox.addEventListener("click", (e) => { 
            if (e.target.classList.contains("new-messages")) {
                e.preventDefault();

                Swal.fire({
                    title: '<h1>New Messages:</h1>',
                    html:messageContainer.innerHTML,
                    showCloseButton: true,
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    focusConfirm: false,
                })
            }
        })
    </script>
</body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact Page{% endblock title %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
        <div class="col-md-6">
            <h2>Contact Us</h2>
            <p>Fill out the form below to get in touch with us.</p>
            <form>
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" class="form-control" id="name" placeholder="Enter your name">
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" class="form-control" id="email" placeholder="Enter your email">
                </div>
                <div class="form-group">
                    <label for="message">Message:</label>
                    <textarea class="form-control" id="message" rows="5" placeholder="Enter your message"></textarea>
                </div>
                <button type="submit" class="btn btn-primary w-100 mt-2">Submit</button>
            </form>
        </div>
        <div class="col-md-6">
            <h2>Our Location</h2>
            <p>Visit us at the following address:</p>
            <address>
            123 Street<br>
            City, State<br>
            Country<br>
            </address>
            <h2>Contact Information</h2>
            <p>Email: TestEmail@gmail.com</p>
            <p>Phone: +1 123-456-7890</p>
        </div>
        </div>
    </div>

{% endblock content %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Home Page{% endblock title %}

{% block content %}    
    <div class="container">
        <h1 class="text-center mt-5 fst-normal mb-5" style="color: #537188">Newest Items</h1>
        <div class="container p-3 d-flex gap-5 flex-wrap justify-content-center" style="background-color: #EEEEEE">
            {% for item in items %}
                <div class="card" style="width: 18rem;">
                    <a href="{% url 'item_detail' item.id %}" style="text-decoration: none; color: black;">
                        <img src="{{item.image.url}}" class="card-img-top" alt="item.name">
                        <div class="card-body">
                            <h5 class="card-title">{{item.name}}</h5>
                            <p class="card-text">Price: ${{item.price}}</p>
                            <a href="{% url 'item_detail' item.id %}" class="btn btn-primary">Item Details</a>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
        <h2 class="text-center mt-5 mb-5">Categories</h2>
        <div class="container p-3 d-flex gap-5 flex-wrap justify-content-center" style="background-color: #EEEEEE">
            {% for category in categories %}
                <a href="{% url 'search' %}?catid={{category.id}}" style="text-decoration:none; color:black;">
                    <div class="card" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">{{category.name}}</h5>
                            <p class="card-text">{{category.items.count}} Items</p>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

core/templates/core/login.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% load socialaccount %}
{% providers_media_js %}

{% block title %}Login{% endblock %}

{% block content %}
<style>
    .errorlist{color:red;}
    h4 {
        width: 100%; 
        text-align: center; 
        border-bottom: 1px solid #DDE6ED; 
        line-height: 0.1em;
        margin: 10px 0 20px; 
        margin-top: 2em;
        margin-bottom: 1.5em;
    } 
    
    h4 span { 
        background:#fff; 
        padding:0 10px;
        color: #9BA4B5;
    }

    .google{
        text-decoration:none;
    }

    @media (max-width: 900px) {
        .cont-form > .card {
            width: 90% !important;
        }
    }

</style>
    {% if messages %}
        <ul class="list-unstyled container">
            {% for message in messages %}
                <li class=
                        "alert text-center alert-dismissible fade show 
                        {% if message.tags == 'error' %}alert-danger
                        {% elif message.tags == 'success' %}alert-success
                        {% elif message.tags == 'warning' %}alert-warning
                        {% else %}alert-info{% endif %}">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    <div class="container d-flex justify-content-center mt-5 cont-form">
        <form method="post" class="card w-50 p-5">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-lg btn-primary" type="submit">Login</button>
        </form>
    </div>
    <h4><span>o</span></h4>
    <p style="font-size: 1.5em;" class="text-center">Also Google Authentication can be used</p>
    <p class="text-center mt-5" style="margin-bottom: 5em;">
        <a class="google" href="{% provider_login_url 'google' %}">
            <button class="btn btn-lg btn-outline-danger" type="button">
                Login with Google
                <i class="bi bi-google"></i>
            </button>
        </a>
    </p>
{% endblock %}

core/templates/core/privacy.html
{% extends 'core/base.html' %}

{% block title %}Privacy Policy Page{% endblock title %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
        <div class="col-md-12">
            <h2>Privacy Policy</h2>
            <p>We are committed to protecting the privacy and confidentiality of our users. This Privacy Policy outlines how we collect, use, and safeguard the personal information you provide to us.</p>
            <h3>Information We Collect</h3>
            <p>When you use our website or services, we may collect certain personally identifiable information, including but not limited to:</p>
            <ul>
            <li>Full name</li>
            <li>Email address</li>
            <li>Contact information</li>
            <li>Other information you voluntarily provide</li>
            </ul>
            <h3>How We Use Your Information</h3>
            <p>We may use the information we collect from you for the following purposes:</p>
            <ul>
            <li>To provide and maintain our services</li>
            <li>To improve our website and services</li>
            <li>To respond to your inquiries or provide customer support</li>
            <li>To send you promotional and marketing communications (if you have opted in)</li>
            <li>To comply with legal obligations</li>
            </ul>
            <h3>Data Security</h3>
            <p>We implement appropriate security measures to protect the confidentiality and integrity of your personal information. However, please be aware that no method of transmission over the internet or electronic storage is completely secure.</p>
            <h3>Third-Party Websites</h3>
            <p>Our website may contain links to third-party websites. We have no control over the privacy practices or content of those websites and are not responsible for the privacy practices or content provided by them.</p>
            <h3>Updates to this Privacy Policy</h3>
            <p>We may update this Privacy Policy from time to time. Any changes will be posted on this page, and the revised version will be effective as of the date it is published.</p>
            <p>If you have any questions or concerns about our Privacy Policy, please contact us at frako789@gmail.com</p>
        </div>
        </div>
    </div>

{% endblock content %}

core/templates/core/signup.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Signup{% endblock %}

{% block content %}
    <style>
        .errorlist{color:red;}

        @media (max-width: 900px) {
            .cont-form > .card {
                width: 90% !important;
            }
        }
    </style>
    <h1 class="text-center mt-5 mb-3">Signup-Form</h1>
    <div class="container d-flex justify-content-center cont-form">
        <form action="" method='POST' class="card w-50 p-5">
            {% csrf_token %}
            {{form|crispy}}
            <input class="btn btn-primary btn-lg mt-3" type="submit" value="Submit">
        </form>
    </div>
{% endblock %}
    
    

core/templates/core/term.html
{% extends 'core/base.html' %}

{% block title %}Term Of users Page{% endblock title %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
        <div class="col-md-12">
            <h2>Terms of Use</h2>
            <p>These Terms of Use outline the rules and regulations for the use of our website and services.</p>
            <h3>Acceptance of Terms</h3>
            <p>By accessing or using our website, you agree to comply with and be bound by these Terms of Use. If you do not agree with any part of these terms, please do not use our website or services.</p>
            <h3>Intellectual Property</h3>
            <p>The content and materials available on our website are the intellectual property of us. All intellectual property rights are reserved.</p>
            <h3>User Conduct</h3>
            <p>When using our website, you agree to the following:</p>
            <ul>
            <li>Do not engage in any unlawful, offensive, or harmful activities</li>
            <li>Do not infringe upon the rights of others</li>
            <li>Do not attempt to gain unauthorized access to our systems or interfere with the website's functionality</li>
            <li>Do not submit false or misleading information</li>
            <li>Do not engage in spamming or other forms of unwanted communication</li>
            </ul>
            <h3>Disclaimer</h3>
            <p>Our website and services are provided on an "as is" and "as available" basis. We make no warranties, expressed or implied, regarding the reliability, accuracy, or availability of our website or services.</p>
            <h3>Limitation of Liability</h3>
            <p>We shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising out of your use or inability to use our website or services.</p>
            <h3>Changes to Terms of Use</h3>
            <p>We reserve the right to modify or replace these Terms of Use at any time. Any changes will be effective immediately upon posting the updated version on our website.</p>
            <h3>Contact Us</h3>
            <p>If you have any questions or concerns about these Terms of Use, please contact us at frako789@gmail.com</p>
        </div>
        </div>
    </div>
{% endblock content %}