conversations/urls.py
from django.urls import path
from .views import create_conversation, inbox, detail

app_name = 'conversation'

urlpatterns = [
    path('<int:item_pk>/', create_conversation, name='new'),
    path('detail/<int:conversation_pk>/', detail, name='detail'),
    path('inbox/', inbox, name='inbox'),
]

core/urls.py
from django.urls import path, include
from .views import (
    index,
    about,
    contact,
    privacy,
    term_of_use,
    signup_view,
    CustomLoginView,
    CustomLogoutView,
    email_exist_with_us,
)

urlpatterns = [
    path("", index, name="home"),
    path("about/", about, name="about"),
    path("contact/", contact, name="contact"),
    path("privacy/", privacy, name="privacy"),
    path("term/", term_of_use, name="term"),
    path("signup/", signup_view, name="signup"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    # Paths for Google authentication
    path("accounts/social/signup/", email_exist_with_us, name="email_exist_with_us"),
    path("accounts/", include("allauth.urls")),
]

item/urls.py
from django.urls import path
from .views import detail, new_item, delete, edit, search

urlpatterns = [
    path('search', search, name='search'),
    path('<int:pk>/', detail, name='item_detail'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('edit/<int:pk>/', edit, name='edit'),
    path('new/', new_item, name='new_item'),
]

marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # paths to views
    path("", include("core.urls")),
    path("items/", include("item.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("conversation/", include("conversations.urls")),
    # paths to admin
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

item/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(verbose_name="Category", max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name = ("Category")
        verbose_name_plural = ("categories")

    def __str__(self):
        return self.name


class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

item/forms.py
from django import forms
from .models import Item


class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image')


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold')

item/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .models import Item, Category
from .forms import NewItemForm, EditItemForm


def search(request):
    query = request.GET.get("query", "")
    category_id = request.GET.get("catid", "")
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()

    if query:
        q = Q(name__icontains=query) | Q(description__icontains=query)
        items = Item.objects.filter(q)

    elif category_id:
        items = items.filter(category=category_id)

    return render(
        request,
        "item/search.html",
        {"items": items, "query": query, "categories": categories},
    )


def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    return render(request, "item/detail.html", {"item": item})


@login_required(login_url="login")
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()
    return redirect("dashboard:index")


@login_required(login_url="login")
def new_item(request):
    if request.method == "POST":
        form = NewItemForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            return redirect("item_detail", pk=item.id)
    else:
        form = NewItemForm()

    return render(request, "item/new_item.html", {"form": form})


@login_required(login_url="login")
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    if request.method == "POST":
        form = EditItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            item.save()
            return redirect("item_detail", pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request, "item/edit_item.html", {"form": form})

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{item.name}}{% endblock %}

{% block content %}
    <style>
        @media (max-width: 900px) {
            .parent-cont {
                flex-wrap: wrap !important;
            }
        }
    </style>
    {% if "message_sent" in request.GET %}
        <div id="alert" class="alert alert-success alert-dismissible fade show text-center container" role="alert">
            Great! Your message has been sent to the seller.
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endif %}
        
    <div class="container mt-5 p-3 d-flex justify-content-center gap-3 parent-cont">
        <div class="container mt-5 p-3 d-flex justify-content-center" style="background-color: #EEEEEE">
            <div class="card" style="width: 25rem;">
                {% if item.image %}
                    <img src="{{item.image.url}}" class="card-img-top" alt="item.name">
                {% endif %}
            </div>
        </div>
        <div class="container mt-5 p-3" style="background-color: #EEEEEE;">
            <h1>{{item.name}}</h1>
            <p><strong>Price: ${{item.price}}</strong></p>
            <p><strong>Seller: {{item.created_by.username}}</strong></p>
            {% if item.description %}
                <p><strong>Description:</strong><br> {{item.description}}</p>
            {% endif %}
            
            {% if request.user == item.created_by %}
                <a href="{% url 'edit' item.id %}"><button type="button" class="btn btn-warning">Edit</button></a>
                <a href="{% url 'delete' item.id %}"><button type="button" class="btn btn-danger">Delete</button></a>
            {% else %}
                <a href="{% url 'conversation:new' item.id %}"><button type="button" class="btn btn-success">Contact Seller</button></a>
            {% endif %}
    
        </div>
    </div>
    <script>
        setTimeout(() => {
            document.getElementById('alert').style.display = 'none';
        }, 3000);
    </script>
{% endblock %}

item/templates/item/edit_item.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Edit Item{% endblock title %}

{% block content %}
    <style>
        .errorlist{color:red;}
        @media(max-width: 1225px) {
            .card{
                width: 100% !important;
            }
        }
    </style>
    <h1 class="text-center mt-5 fst-normal mb-3" style="color: #537188">Edit Item</h1>
    <div class="container d-flex justify-content-center">
        <form action="" method='POST' class="card w-50 p-5" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <input class="btn btn-primary btn-lg mt-3" type="submit" value="Submit">
        </form>
    </div>
{% endblock content %}
    
    

item/templates/item/new_item.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}

{% block title %}New Item{% endblock title %}

{% block content %}
    <style>
        .errorlist{color:red;}

        @media (max-width: 900px) {
            .cont-form>.card{
                width: 95% !important;

            }
        }
    </style>
    <h1 class="text-center mt-5 fst-normal mb-3" style="color: #537188">Add New Item</h1>
    <div class="container d-flex justify-content-center cont-form">
        <form action="" method='POST' class="card w-50 p-5" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <input class="btn btn-primary btn-lg mt-3" type="submit" value="Submit">
        </form>
    </div>
{% endblock content %}
    
    

item/templates/item/search.html
{% extends 'core/base.html' %}

{% block title %}Search Items{% endblock %}

{% block content %}
    <style>
        @media (max-width: 900px) {
            .search-cont{
                flex-wrap: wrap !important;
                
            }
            .search-cont > input{
                width: 80% !important;
                margin-bottom: 0.5em !important;
                margin-left: auto !important;
                margin-right: auto !important;
            }
            .search-cont > div{
                width: 100% !important;
                display: flex;
                justify-content: center;
                gap: 0.5em;
            }
        }
    </style>

    <h1 class="text-center mt-5 mb-5 fst-normal" style="color: #537188">Search Items</h1>
    <div class="container d-flex justify-content-center mb-3">
        <form action="">
            <div class="form-group d-flex search-cont">
                <input style="width: 25em;" id="search" type="text" name="query" class="form-control text-center" value="{{query}}" placeholder="Type to Search">
                <div class="container w-50">
                    <button type="submit" class="btn btn-primary">Search</button>
                    <a href="{% url 'search' %}" type="button" class="btn btn-secondary">Reset</a>
                </div>
            </div>
        </form>
    </div>
    <div class="container d-flex justify-content-center mb-5">
        <ul class="d-flex gap-4 d-flex flex-wrap">
            {% for cat in categories %}
                <li style="list-style: none;">
                    <a style=" color: #537188;" href="{% url 'search' %}?catid={{cat.id}}">{{cat.name}}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="container">
        <div class="container p-3 d-flex gap-5 flex-wrap justify-content-center" style="background-color: #EEEEEE">
            {% for item in items %}
                <div class="card" style="width: 18rem;">
                    <a href="{% url 'item_detail' item.id %}" style="text-decoration: none; color: black;">
                        <img src="{{item.image.url}}" class="card-img-top" alt="item.name">
                        <div class="card-body">
                            <h5 class="card-title">{{item.name}}</h5>
                            <p class="card-text">Price: ${{item.price}}</p>
                            <a href="{% url 'item_detail' item.id %}" class="btn btn-primary">Item Details</a>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
{% endblock %}
    